### ISSUE TITLE
Alkalmazás hiba

### ISSUE THREAD

**Issue by bence1300** [klnorbert/RFT#2]
Találtam egy hibát az alkalmazásban kijavítottam és megosztottam itt 
a 27. sorban kicseréltem az int típusú változót egy long típusú változóra mert az int túl kicsinek bizonyult 
Szeretném majd ha rá néznétek @danielordogh94  @klnorbert
Ha van valami amit láttok hogy módosítani kéne vagy nem jó akkor szóljatok

**Comment by klnorbert** [comment]
jó ötlet megoldásnak én elfogadom a változtatásod

**Comment by danielordogh94** [comment]
Ránéztem, szerintem mehet

**Comment by klnorbert** [comment]
csakis én zárhatom le

**Comment by klnorbert** [comment]
most
